# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c19c14633e7c59fa55e05744d7931e6810aab5881caabd7d4733e11bd8b5f3c9e8a6473ab3999b519d07db86ec1388f3e5db0da163d95fc095f071e826a1625

test:
  secret_key_base: 6da11283ff8f9a63c8bace32cda4d0aee99818df6f3ed8d55c3aa5f7480612164589396e88e5535fd1d87e07883699ec65fb1b9999d8cdcce6c6ca1242a903c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
